[metadata]
name = "fp-data-toolbox"
version = "0.1.19"
description = "personal toolbox for data science"
author = "Fred Pires"
author_email = "fredapires@gmail.com"
long_description = "file: README.md"
license = "MIT"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[build-system]
requires = [
    "pipenv", 
    "setuptools", 
    "wheel"
]
build-backend = "setuptools.build_meta"
