[metadata]
name = "fp-data-toolbox"
version = "0.1.20"
description = "personal toolbox for data science"
author = "Fred Pires"
author_email = "fredapires@gmail.com"
long_description = "file: README.md"

[build-system]
requires = [
    "pipenv", 
    "setuptools", 
    "wheel"
]
build-backend = "setuptools.build_meta"
