[tool.poetry]
name = "fp-data-toolbox"
version = "0.1.19"
description = "personal toolbox for data science"
authors = ["fredapires <fredapires@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "fp_data_toolbox"}]



[tool.poetry.dependencies]
python = "^3.8"
build = "*"
pytest = "*"
faker = "*"
numpy = "1.23"
pandas = "*"
missingno = "*"
dataprep = "*"
matplotlib = "*"
seaborn = "*"
pandas-profiling = "*"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


