
/*
    THIS IS AN EXAMPLE PROCEDURE FOR CREATING A TABLE IN GBQ. IT HAS A LOT OF METADATA COMPONENTS ADDED AND CAN BE A REFERENCE FOR REAL PROCEDURES.
    TO ACTUALLY CREATE THE PROCEDURE AND THEN INVOKE IT, UNCOMMENT THE LINES BELOW AND RUN THE FULL STATEMENT. 
*/


-- CREATE OR REPLACE PROCEDURE `analytics-scfinance-thd.TEMP_1DAY.USP_CREATE_A_TABLE`()
-- OPTIONS (strict_mode=true, description="A table")

/*
    IF YOU WANT TO SEE HOW THE PROCEDURE RUNS AND VIEW THE OUTPUT BUT DON'T NEED THE PROCEDURE STATEMENT CREATED, RUN ONLY THE FOLLOWING. THIS WILL CREATE THE TEMP TABLE WITH A 1 MINUTE EXPIRATION. YOU CAN MODIFY THE EXPIRATION TIMESTAMP TO BE LONGER IF YOU WANT TO KEEP THE TABLE AROUND FOR LONGER.
*/
BEGIN

    DECLARE EXPIRATION_INTERVAL = 5; --MINUTES

    /*
        THIS STATEMENT CAN BE RUN AND WILL BE VALID FOR <EXPIRATION_INTERVAL> MINUTES (SEE THE EXPIRATION TIMESTAMP). FEEL FREE TO RUN THIS AND LOOK AT THE METADATA IN GBQ..
    */

    CREATE OR REPLACE TABLE `analytics-scfinance-thd.TEMP_1DAY.A_TABLE`
    (

    FIELD_1 INT64 DEFAULT 0 OPTIONS(description="Field 1"),
    FIELD_2 STRING NOT NULL OPTIONS(description="Field 2"),
    FIELD_3 BOOL NOT NULL OPTIONS(description="Field 3"),
    FIELD_4 DATE OPTIONS(description="Field 4"),
    FIELD_5 TIMESTAMP OPTIONS(description="Field 5"),
    FIELD_6 FLOAT64 DEFAULT 0.0 OPTIONS(description="Field 6"),
    FIELD_7 DECIMAL(10,2) DEFAULT 10000000.01 OPTIONS(description="Field 7"),
    PRIMARY KEY(FIELD_2, FIELD_3) NOT ENFORCED 
    )
    OPTIONS(
        labels=[("key", "value")], -- MUST BE LOWERCASE
        description="A Table of Bees",
        expiration_timestamp = CURRENT_TIMESTAMP() + INTERVAL 5 MINUTE
    )
    AS 
    (
        SELECT
            FIELD_1,
            FIELD_2,
            FIELD_3,
            FIELD_4,
            FIELD_5,
            FIELD_6,
            FIELD_7
        FROM
            `project.DATASET.TABLE`
    )
    PARTITION BY
    FIELD_1

    CLUSTER BY 
    FIELD_2;


END;