CREATE OR REPLACE PROCEDURE `analytics-scfinance-thd.TEMP_1DAY.USP_CREATE_A_TABLE`()
/*
    OPTIONS ADD TO THE DETAILS PANE IN GBQ FOR THE PROCEDURE. 
    
    1. STRICT_MODE IS A BOOLEAN SPECIFYING WHETHER A PROCEDURE SHOULD BE EVALUDATED BY GOOGLE FOR CORRECTNESS. IF TRUE, ONLY VALID PROCEDURES CAN BE SAVED. IF FALSE, A PROCEDURE THAT CONTAINS INVALID SQL CAN BE SAVED.
    2. DESCRIPTION IS A STRING THAT DESCRIBES THE PROCEDURE.
*/

OPTIONS (strict_mode=true, description="A table")



BEGIN

    /*
        YOUR QUERIES HERE
    */


END;