-- aggregating to DC/WEEK
WITH base AS 
  (SELECT MODEL_NAME, 
    PLATFORM, 
    ORIG_LOC_NBR, 
    FSCL_YR_WK, 
    FCST_LAG, 
    SUM(FCST_FLOW) AS FCST_FLOW, 
    SUM(BSLN_FLOW) AS BSLN_FLOW, 
    SUM(ABS(ACT_FLOW)) AS ACT_FLOW, -- to be used with WMAPE metric
    ABS(SUM(ACT_FLOW) - SUM(BSLN_FLOW)) AS BSLN_ABS_DIFF,
    ABS(SUM(ACT_FLOW) - SUM(FCST_FLOW)) AS FCST_ABS_DIFF
  FROM ``  
  WHERE DATA_GRANULARITY = 'DC/WEEK'
  AND MODEL_NAME != 'BASELINE_FCST'
  AND ORIG_LOC_NBR IS NOT NULL
  AND FSCL_YR_WK BETWEEN '202301' AND '202345'
  AND SNSH_YR_WK BETWEEN '202301' AND '202345'
  GROUP BY 1,2,3,4,5),

-- calculating WMAPE
calc AS
(
  SELECT MODEL_NAME, PLATFORM, FCST_LAG, SUM(BSLN_ABS_DIFF) / SUM(ACT_FLOW) AS BSLN_WMAPE, SUM(FCST_ABS_DIFF) / SUM(ACT_FLOW) AS FCST_WMAPE
  FROM base  
  GROUP BY 1,2,3
)

-- getting best model WMAPE in each category
SELECT * FROM calc 
QUALIFY 1 = ROW_NUMBER() OVER(PARTITION BY PLATFORM, FCST_LAG ORDER BY FCST_WMAPE ASC)
ORDER BY PLATFORM, FCST_LAG;
