# generated by chatGPT on 01/27/23

import pytest

class TestExample:
    def test_one_plus_one(self):
        assert 1 + 1 == 2

    def test_two_times_two(self):
        assert 2 * 2 == 4

    @pytest.mark.parametrize("input_, output", [(3, 4), (4, 5), (5, 6)])
    def test_increment(self, input_, output):
        assert input_ + 1 == output

    @pytest.mark.skip(reason="skip this test for now")
    def test_skip(self):
        assert 1 == 0

    def test_assertion_error(self):
        with pytest.raises(AssertionError):
            assert 1 == 0
