CREATE OR REPLACE PROCEDURE ``()

BEGIN 

/*


  PURPOSE:
  THIS PROCEDURE TAKES THE AVERAGE AND MEDIAN OF FLOW FORECAST OUTPUTS FROM THE BETA 1.0 MODEL, LEGACY MODEL, AND OFE.
  
  DESCRIPTION:
  GRABS ROWS FOR CURRENT SNAP WEEK FROM BETA 1.0 AND OFE, AND ROWS FOR CURRENT SNAP WEEK - 1 FOR LEGACY MODEL. 
  AVERAGES THE OUTPUT OR TAKES THE MEDIAN. INSERTS ROWS INTO THE BETA FORECAST STG TABLE DEPENDING ON USER'S CHOICE OF ENSEMBLE METHOD.
  
UPDATED PARAMETER(S): 
  tablenames : STRING ARRAY (OR LIST) OF TABLES, STORING ALIGNED AND SCOPE MODEL OUTPUTS, WHICH WILL BE USED AS INPUT FOR PERFROMING THE ENSEMBLE
  E.G. ['analytics-scfinance-thd.TEMP_30DAY.TABLE_A', 'analytics-scfinance-thd.TEMP_30DAY.TABLE_B']

  ensemble_method: EITHER AVERAGE OR MEDIAN. USED TO DETERMINE WHICH ENSEMBLE IS INSERTED INTO BETA STG TABLE.
  ACCEPTED VALUES : 'MEDIAN' OR 'AVERAGE'

*/


DECLARE SNSH_YR_WK_VAR STRING;
DECLARE i INT64 DEFAULT 0;
DECLARE num_tables INT64;
DECLARE QUERY STRING;


SET SNSH_YR_WK_VAR = (SELECT `analytics-scfinance-thd.SHARED.UDF_GET_CURR_SNSH_FW`());
SET num_tables = ARRAY_LENGTH(tablenames);

--=======================================================================
-- CREATE TEMPORARY STAGING TABLE
--=======================================================================
 
CREATE OR REPLACE TABLE  `analytics-scfinance-thd.TEMP_1DAY.FLOW_FCST_OUTPUT_ENSEMBLE_STG1`
(
  MODEL_NAME STRING, 
  SNSH_YR_WK STRING, 
  FSCL_YR_WK STRING, 
  PLATFORM STRING, 
  ORIG_LOC_NBR STRING, 
  DEPT_CLASS STRING, 
  FLOW FLOAT64
);

--RUN LOOP BASED ON THE NUMBER OF INPUT TABLES FOR WHICH WE NEED TO PERFORM ENSEMBLING
-- THE LOOP WILL INSERT THE RESULTS OF THE INDIVIDUAL TABLES AND MODELS INTO THE STG_1 TABLE
WHILE i < num_tables
  DO

   EXECUTE IMMEDIATE FORMAT ("""
    INSERT INTO  `analytics-scfinance-thd.TEMP_1DAY.FLOW_FCST_OUTPUT_ENSEMBLE_STG1`
    (
    MODEL_NAME, 
    SNSH_YR_WK, 
    FSCL_YR_WK, 
    PLATFORM, 
    ORIG_LOC_NBR, 
    DEPT_CLASS, 
    FLOW
    )
    SELECT TRIM(MODEL_NAME) AS MODEL_NAME, 
    SNSH_YR_WK, 
    FSCL_YR_WK, 
    TRIM(PLATFORM) AS PLATFORM, 
    TRIM(ORIG_LOC_NBR) AS ORIG_LOC_NBR, 
    TRIM(DEPT_CLASS) AS DEPT_CLASS, 
    SUM(METRIC_VAL) AS FLOW
    FROM `%s`
    WHERE FSCL_YR_WK BETWEEN @SNSH_YR_WK_VAR AND '202453'
    GROUP BY 1,2,3,4,5,6;
    """,tablenames[i])
    USING SNSH_YR_WK_VAR AS SNSH_YR_WK_VAR;

  SET i = i + 1;


END WHILE;

--====================================================================
-- CALCULATE MEDIAN AND AVERAGE OF THE UNION BASED ON STG_1 TABLE
--====================================================================

CREATE OR REPLACE TABLE `analytics-scfinance-thd.TEMP_1DAY.FLOW_FCST_OUTPUT_ENSEMBLE_STG2`
AS

WITH ORDERED AS 
  (
    SELECT *
    FROM  `analytics-scfinance-thd.TEMP_1DAY.FLOW_FCST_OUTPUT_ENSEMBLE_STG1`
    ORDER BY SNSH_YR_WK, FSCL_YR_WK, PLATFORM, ORIG_LOC_NBR, DEPT_CLASS, FLOW
  ),
  MEDIAN AS 
  (
    SELECT DISTINCT 'MEDIAN' AS MODEL_ID, 
    SNSH_YR_WK, 
    FSCL_YR_WK, 
    PLATFORM, 
    ORIG_LOC_NBR, 
    DEPT_CLASS,
    PERCENTILE_CONT(FLOW,0.5) OVER(PARTITION BY SNSH_YR_WK, FSCL_YR_WK, PLATFORM, ORIG_LOC_NBR, DEPT_CLASS) AS METRIC_VAL
    FROM ORDERED
  ),
  AVERAGE AS 
  (
    SELECT 'AVERAGE' AS MODEL_ID, 
    SNSH_YR_WK, 
    FSCL_YR_WK, 
    PLATFORM, 
    ORIG_LOC_NBR, 
    DEPT_CLASS, 
    AVG(FLOW) AS METRIC_VAL
    FROM `analytics-scfinance-thd.TEMP_1DAY.FLOW_FCST_OUTPUT_ENSEMBLE_STG1`
    GROUP BY 1,2,3,4,5,6
  )
  SELECT * 
  FROM MEDIAN
  UNION ALL
  SELECT * 
  FROM AVERAGE;


--========================================================================
-- CREATE/INSERT TOGETHER RESULTS OF DIFFERENT MODELS USING STG_2 RESULTS
--========================================================================

CREATE OR REPLACE TABLE `analytics-scfinance-thd.TEMP_1DAY.FLOW_FCST_OUTPUT_ENSEMBLE_FINAL` 
AS 
(
  SELECT 'MODEL_FCST' AS DATA_CATEGORY,
    'DC/CLASS/WEEK' AS DATA_GRANULARITY,
    'FORECAST' AS ACT_FCST_FLAG,
    CONCAT('BETA1_LEGACY_OFE_ENSEMBLE','_',ensemble_method) AS MODEL_NAME,
    CONCAT(ensemble_method, ' ensemble model of OFE, legacy, and beta 1.0 model outputs.') AS MODEL_DESC,
    SNSH_YR_WK,
    FSCL_YR_WK,
    PLATFORM,
    ORIG_LOC_NBR,
    'null' AS DEST_LOC_NBR,
    DEPT_CLASS,
    'OB_FLOW' AS METRIC,
    METRIC_VAL, 
    CURRENT_DATETIME() AS LAST_UPD_TS
  FROM `analytics-scfinance-thd.TEMP_1DAY.FLOW_FCST_OUTPUT_ENSEMBLE_STG2`
  WHERE MODEL_ID = ensemble_method
);


END;
